apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nonprod-dev
spec:
  sourceRepos:
    - 'https://github.com/argoproj/argocd-example-apps'
  destinations:
    - namespace: 'dev'
    - server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
