apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nonprod-dev
spec:
  sourceRepos:
    - 'https://github.com/argoproj/argocd-example-apps'
    - 'https://github.com/primozh/argocd-example-parent'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
