apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-appbundle-app-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    name: in-cluster
  project: nonprod-dev
  source:
    path: apps/dev
    repoURL: https://github.com/primozh/argocd-example-parent
    targetRevision: HEAD